---
sudo: required

language: python

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - >
    mkdir /tmp/docker; echo '{
    "experimental": true,
    "storage-driver": "overlay2"
    }' | sudo tee /etc/docker/daemon.json;  sudo service docker restart
  - docker info

install:
  - pip install -r requirements.txt

env:
  - SCENARIO=ubuntu
  - SCENARIO=centos
  - SCENARIO=default

script: "molecule test --scenario-name $SCENARIO"
