---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: default
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: docker-db-debian-11
    image: debian:11
    command: /lib/systemd/systemd
    privileged: true
    volumes:
      - /tmp/docker-db-debian-11:/var/lib/docker
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      gather_timeout: 30
      interpreter_python: auto
      jinja2_extensions: jinja2.ext.do
      timeout: 30
    ssh_connection:
      pipelining: true
verifier:
  name: testinfra
